# Generated by Django 3.0.5 on 2020-07-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='news.NewsItem'),
        ),
    ]
